name: adhub
description: "A Flutter package that simplifies ad integration with a unified API for banner, interstitial, and rewarded ads."
version: 0.0.3
homepage: https://github.com/RajNarola29/adhub.git

environment:
  sdk: ^3.10.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  get: ^4.6.6
  dio: ^5.4.0
  flutter_hooks: ^0.21.3+1
  logger: ^2.4.0
  in_app_review: ^2.0.9
  package_info_plus: ^9.0.0
  google_mobile_ads: ^7.0.0
  applovin_max: ^4.5.2
  app_tracking_transparency: ^2.0.6
  onesignal_flutter: ^5.3.4
  url_launcher: ^6.3.2
  loading_animation_widget: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0